[package]
name = "estrannaise-rs-web"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
estrannaise_rs = { path = "../estrannaise-rs-lib" }
getrandom = { version = "0.3.0", features = ["wasm_js"] }
wasm-bindgen = "0.2.100"
